In [1]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

In [98]:
with  open('vishal_new.html','r',encoding='utf-8') as f:
    res=f.read()
soup=BeautifulSoup(res,'html.parser')
mobile_name=soup.find_all('div',class_="_4rR01T")
star=soup.find_all('div',class_='_3LWZlK')
ratings=soup.find_all('span',class_='_2_R_DZ')

print(mobile_name[0].text)
print(star[0].text)
print(ratings[0].text.split('&')[0].strip())

Huawei P9 (Mystic Silver, 32 GB)
4.5
829 Ratings

In [100]:
df=pd.DataFrame({'mobile_name':[],'star':[],'ratings':[],'reviews':[],'final price':[],'old price':[],'display':[],'camera':[],'discount':[]})

In [103]:
d={'mobile_name':[],'star':[],'ratings':[],'reviews':[],'final price':[],'old price':[],'display':[],'camera':[],'discount':[]}
box=soup.find_all('div',class_='_3pLy-c row')
for i in box:
    try:
        d['mobile_name'].append(i.find('div',class_="_4rR01T").text.strip())
        d['star'].append(float(i.find('div',class_='_3LWZlK').text.strip()))
        d['ratings'].append(i.find('span',class_='_2_R_DZ').text.split('&')[0][0:-8].strip())
        d['reviews'].append(i.find('span',class_='_2_R_DZ').text.split('&')[1][1:-8].strip())
        d['display'].append(i.find('ul',class_='_1xgFaf').find_all('li')[1].text.strip())
        d['camera'].append(i.find('ul',class_='_1xgFaf').find_all('li')[2].text.strip())
        d['final price'].append(i.find('div',class_='_30jeq3 _1_WHN1').text[1:].strip().replace(',',''))
        d['old price'].append(i.find('div',class_='_3I9_wc _27UcVY').text.strip())
        # d['discount'].append(i.find('div',class_='_3Ay6Sb').text.split()[0].strip()[0:i.find('div',class_='_3Ay6Sb').text.split()[0].find("%")])
        d['discount'].append(i.find('div',class_='_3Ay6Sb').text.strip()[:-5])
    except:
        d['old price'].append(np.nan)
        d['discount'].append(np.nan)
    # d['final price'].append(i.find('div',class_='_25b18c').text.strip())
df1=pd.DataFrame(d)
df1

,mobile_name,star,ratings,reviews,final price,old price,display,camera,discount
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,829,265,39999,"₹40,999",13.21 cm (5.2 inch) Full HD Display,12MP + 12MP | 8MP Front Camera,2
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,829,265,39999,"₹40,999",13.21 cm (5.2 inch) Full HD Display,12MP + 12MP | 8MP Front Camera,2
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,"3,234",364,49999,"₹1,01,999",16.76 cm (6.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,50
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,"4,262",285,44999,"₹95,999",17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,53
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,559,96,49999,"₹74,999",16.94 cm (6.67 inch) Full HD+ Display,200MP + 50MP + 12MP | 60MP Front Camera,33
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,559,96,49999,"₹74,999",16.94 cm (6.67 inch) Full HD+ Display,200MP + 50MP + 12MP | 60MP Front Camera,33
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,415,39,40999,"₹45,999",16.26 cm (6.4 inch) Full HD+ Display,50MP + 12MP + 5MP | 32MP Front Camera,10
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,246,35,46999,"₹47,999",16.64 cm (6.55 inch) Display,48MP + 2MP + 16MP,2
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,"3,234",364,49999,"₹1,01,999",16.76 cm (6.6 inch) Full HD+ Display,50MP + 12MP + 10MP | 10MP Front Camera,50
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,246,35,47349,"₹47,999",16.64 cm (6.55 inch) Display,48MP + 2MP + 16MP,1
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,"3,688",552,38849,"₹47,999",16.94 cm (6.67 inch) Full HD+ Display,108MP + 13MP + 5MP | 20MP Front Camera,19
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,"4,262",285,44999,"₹95,999",17.02 cm (6.7 inch) Full HD+ Display,12MP + 12MP | 10MP Front Camera,53
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,970,142,49999,"₹57,990",16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,13
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,970,142,47999,"₹57,990",16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,17
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,274,26,48999,NaN,16.81 cm (6.62 inch) Display,50MP Rear Camera,NaN
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,274,26,46999,NaN,16.81 cm (6.62 inch) Display,50MP Rear Camera,NaN
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4.0,286,30,49999,NaN,16.64 cm (6.55 inch) Display,48MP Rear Camera,NaN
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,"1,95,660","11,232",46999,"₹48,900",15.49 cm (6.1 inch) Liquid Retina HD Display,12MP + 12MP | 12MP Front Camera,3
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,369,37,49999,NaN,16.64 cm (6.55 inch) Display,48MP Rear Camera,NaN
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,246,35,43990,"₹79,990",17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,45
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,246,35,43900,"₹79,990",17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,45
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,"2,866",436,49999,"₹57,999",17.02 cm (6.7 inch) Quad HD Display,50MP + 50MP + 2MP | 32MP Front Camera,13
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,"3,791",691,48999,"₹54,990",16.66 cm (6.56 inch) Full HD+ Display,50MP + 12MP + 12MP + 8MP | 32MP Front Camera,10
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,218,28,48880,"₹84,999",17.09 cm (6.73 inch) Full HD+ Display,50MP + 50MP + 50MP | 32MP Front Camera,42

In [77]:
box[0].find('div',class_='_3Ay6Sb').text.strip()

'2% off'

In [105]:
with open('List of state and union territory capitals in India - Wikipedia (5_28_2025 8：46：50 AM).html','r',encoding='utf-8') as f:
    res=f.read()
soup=BeautifulSoup(res,'html.parser')
box=soup.find_all('table',class_='wikitable sortable jquery-tablesorter')
box

[<table class="wikitable sortable jquery-tablesorter">
 <thead><tr>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">State
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Administrative/<br/>Executive capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Legislative capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Judicial capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Year of<br/>establishment
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Former capital
 <tbody>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Andhra_Pradesh" title="Andhra Pradesh">Andhra Pradesh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Amaravati" title="Amaravati">Amaravati</a>
 </td>
 <td>Amaravati
 </td>
 <td>Amaravati
 </td>
 <td>1956
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Hyderabad" title="Hyderabad">Hyderabad</a><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a></sup>(1956–2014)
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Arunachal_Pradesh" title="Arunachal Pradesh">Arunachal Pradesh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Itanagar" title="Itanagar">Itanagar</a>
 </td>
 <td>Itanagar
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
 </td>
 <td>1987
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Assam" title="Assam">Assam</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Dispur" title="Dispur">Dispur</a>
 </td>
 <td>Dispur
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
 </td>
 <td>1972
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Shillong" title="Shillong">Shillong</a><sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a></sup> (1950–1972)
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Bihar" title="Bihar">Bihar</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Patna" title="Patna">Patna</a>
 </td>
 <td>Patna
 </td>
 <td>Patna
 </td>
 <td>1950
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Chhattisgarh" title="Chhattisgarh">Chhattisgarh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Raipur" title="Raipur">Raipur</a><sup class="reference" id="cite_ref-6"><a href="#cite_note-6"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>Raipur
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Bilaspur,_Chhattisgarh" title="Bilaspur, Chhattisgarh">Bilaspur</a>
 </td>
 <td>2000
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Goa" title="Goa">Goa</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Panaji" title="Panaji">Panaji</a><sup class="reference" id="cite_ref-8"><a href="#cite_note-8"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a></sup>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Porvorim" title="Porvorim">Porvorim</a>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Mumbai" title="Mumbai">Mumbai</a>
 </td>
 <td>1987
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Gujarat" title="Gujarat">Gujarat</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Gandhinagar" title="Gandhinagar">Gandhinagar</a>
 </td>
 <td>Gandhinagar
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a>
 </td>
 <td>1960
 </td>
 <td>Ahmedabad (1960–1970)
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Haryana" title="Haryana">Haryana</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
 </td>
 <td>Chandigarh
 </td>
 <td>Chandigarh
 </td>
 <td>1966
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Himachal_Pradesh" title="Himachal Pradesh">Himachal Pradesh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Shimla" title="Shimla">Shimla</a>
 </td>
 <td>Shimla (Summer)<br/><a href="https://en.wikipedia.org/wiki/Dharamshala" title="Dharamshala">Dharamshala</a> (Winter)<sup class="reference" id="cite_ref-9"><a href="#cite_note-9"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>Shimla
 </td>
 <td>1971
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Jharkhand" title="Jharkhand">Jharkhand</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Ranchi" title="Ranchi">Ranchi</a>
 </td>
 <td>Ranchi
 </td>
 <td>Ranchi
 </td>
 <td>2000
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Karnataka" title="Karnataka">Karnataka</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Bengaluru" title="Bengaluru">Bengaluru</a>
 </td>
 <td>Bengaluru (Summer)<br/><a href="https://en.wikipedia.org/wiki/Belgaum" title="Belgaum">Belgaum</a> (Winter)
 </td>
 <td>Bengaluru
 </td>
 <td>1956
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Kerala" title="Kerala">Kerala</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Thiruvananthapuram" title="Thiruvananthapuram">Thiruvananthapuram</a>
 </td>
 <td>Thiruvananthapuram
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Kochi" title="Kochi">Kochi</a><sup class="reference" id="cite_ref-10"><a href="#cite_note-10"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>1956
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Madhya_Pradesh" title="Madhya Pradesh">Madhya Pradesh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Bhopal" title="Bhopal">Bhopal</a>
 </td>
 <td>Bhopal
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Jabalpur" title="Jabalpur">Jabalpur</a>
 </td>
 <td>1956
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Maharashtra" title="Maharashtra">Maharashtra</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Mumbai" title="Mumbai">Mumbai</a><sup class="reference" id="cite_ref-11"><a href="#cite_note-11"><span class="cite-bracket">[</span>e<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>Mumbai (Summer)<br/><a href="https://en.wikipedia.org/wiki/Nagpur" title="Nagpur">Nagpur</a> (Winter)
 </td>
 <td>Mumbai
 </td>
 <td>1960
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Manipur" title="Manipur">Manipur</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Imphal" title="Imphal">Imphal</a>
 </td>
 <td>Imphal
 </td>
 <td>Imphal
 </td>
 <td>1972
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Meghalaya" title="Meghalaya">Meghalaya</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Shillong" title="Shillong">Shillong</a>
 </td>
 <td>Shillong
 </td>
 <td>Shillong
 </td>
 <td>1972
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Mizoram" title="Mizoram">Mizoram</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Aizawl" title="Aizawl">Aizawl</a>
 </td>
 <td>Aizawl
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
 </td>
 <td>1987
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Nagaland" title="Nagaland">Nagaland</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Kohima" title="Kohima">Kohima</a>
 </td>
 <td>Kohima
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
 </td>
 <td>1963
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Odisha" title="Odisha">Odisha</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Bhubaneswar" title="Bhubaneswar">Bhubaneswar</a>
 </td>
 <td>Bhubaneswar
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Cuttack" title="Cuttack">Cuttack</a>
 </td>
 <td>1950
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Punjab,_India" title="Punjab, India">Punjab</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
 </td>
 <td>Chandigarh
 </td>
 <td>Chandigarh
 </td>
 <td>1966
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Rajasthan" title="Rajasthan">Rajasthan</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Jaipur" title="Jaipur">Jaipur</a>
 </td>
 <td>Jaipur
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Jodhpur" title="Jodhpur">Jodhpur</a>
 </td>
 <td>1950
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Sikkim" title="Sikkim">Sikkim</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Gangtok" title="Gangtok">Gangtok</a><sup class="reference" id="cite_ref-13"><a href="#cite_note-13"><span class="cite-bracket">[</span>f<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>Gangtok
 </td>
 <td>Gangtok
 </td>
 <td>1975
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Tamil_Nadu" title="Tamil Nadu">Tamil Nadu</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Chennai" title="Chennai">Chennai</a><sup class="reference" id="cite_ref-14"><a href="#cite_note-14"><span class="cite-bracket">[</span>g<span class="cite-bracket">]</span></a></sup>
 </td>
 <td>Chennai
 </td>
 <td>Chennai
 </td>
 <td>1956
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Telangana" title="Telangana">Telangana</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Hyderabad" title="Hyderabad">Hyderabad</a>
 </td>
 <td>Hyderabad
 </td>
 <td>Hyderabad
 </td>
 <td>2014
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Tripura" title="Tripura">Tripura</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Agartala" title="Agartala">Agartala</a>
 </td>
 <td>Agartala
 </td>
 <td>Agartala
 </td>
 <td>1972
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Uttar_Pradesh" title="Uttar Pradesh">Uttar Pradesh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Lucknow" title="Lucknow">Lucknow</a>
 </td>
 <td>Lucknow
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Prayagraj" title="Prayagraj">Prayagraj</a>
 </td>
 <td>1950
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Uttarakhand" title="Uttarakhand">Uttarakhand</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Dehradun" title="Dehradun">Dehradun</a>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Bhararisain" title="Bhararisain">Bhararisain</a> (summer)<sup class="reference" id="cite_ref-15"><a href="#cite_note-15"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup><br/>Dehradun (winter)
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Nainital" title="Nainital">Nainital</a>
 </td>
 <td>2000
 </td>
 <td> —
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/West_Bengal" title="West Bengal">West Bengal</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Kolkata" title="Kolkata">Kolkata</a>
 </td>
 <td>Kolkata
 </td>
 <td>Kolkata
 </td>
 <td>1950
 </td>
 <td> —
 <tfoot></tfoot></td></tr></tbody></th></tr></thead></table>,
 <table class="wikitable sortable jquery-tablesorter" width="90%">
 <thead><tr>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending" width="25%">Union Territory
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Administrative/<br/>Executive capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Legislative capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Judicial capital
 </th>
 <th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Year of<br/>establishment
 <tbody>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Andaman_and_Nicobar_Islands" title="Andaman and Nicobar Islands">Andaman and Nicobar Islands</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Port_Blair" title="Port Blair">Port Blair</a>
 </td>
 <td>–
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Kolkata" title="Kolkata">Kolkata</a>
 </td>
 <td>1956
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
 </td>
 <td>–
 </td>
 <td>Chandigarh
 </td>
 <td>1966
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Dadra_and_Nagar_Haveli_and_Daman_and_Diu" title="Dadra and Nagar Haveli and Daman and Diu">Dadra and Nagar Haveli and Daman and Diu</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Daman,_India" title="Daman, India">Daman</a>
 </td>
 <td>–
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Mumbai" title="Mumbai">Mumbai</a>
 </td>
 <td>2020
 </td></tr>
 <tr>
 <td><a href="https://en.wikipedia.org/wiki/Jammu_and_Kashmir_(union_territory)" title="Jammu and Kashmir (union territory)"><b>Jammu and Kashmir</b></a>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Srinagar" title="Srinagar">Srinagar</a> (summer)<br/><a href="https://en.wikipedia.org/wiki/Jammu" title="Jammu">Jammu</a> (winter)
 </td>
 <td>Srinagar (summer)<br/>Jammu (winter)
 </td>
 <td>Srinagar (summer)<br/>Jammu (winter)
 </td>
 <td>2019
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Ladakh" title="Ladakh">Ladakh</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Leh" title="Leh">Leh</a> (summer)<br/><a href="https://en.wikipedia.org/wiki/Kargil" title="Kargil">Kargil</a> (winter)
 </td>
 <td>–
 </td>
 <td>Srinagar (summer)<br/>Jammu (winter)
 </td>
 <td>2019
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Lakshadweep" title="Lakshadweep">Lakshadweep</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Kavaratti" title="Kavaratti">Kavaratti</a>
 </td>
 <td>–
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Ernakulam" title="Ernakulam">Ernakulam</a>
 </td>
 <td>1956
 </td></tr>
 <tr>
 <td><b><a href="https://en.wikipedia.org/wiki/Delhi" title="Delhi">Delhi</a></b>
 </td>
 <td><a href="https://en.wikipedia.org/wiki/New_Delhi" title="New Delhi">New Delhi</a>
 </td>
 <td>New Delhi
 </td>
 <td>New Delhi
 </td>
 <td>1956
 </td></tr>
 <tr>
 <td><a href="https://en.wikipedia.org/wiki/Puducherry_(union_territory)" title="Puducherry (union territory)"><b>Puducherry</b></a>
 </td>
 <td><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Puducherry_(city)" title="Puducherry (city)">Pondicherry</a>
 </td>
 <td>Pondicherry
 </td>
 <td><a href="https://en.wikipedia.org/wiki/Chennai" title="Chennai">Chennai</a>
 </td>
 <td>1951
 </td></tr>
 <tfoot></tfoot></tbody></th></tr></thead></table>]

AttributeError: ResultSet object has no attribute "find". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [112]:
state=box[0]
head=state.find('thead')
col=[]
for i in head.find_all('th'):
    col.append(i.text.strip())
col[5]=col[5].split('\n')[0]
col

['State',
 'Administrative/Executive capital',
 'Legislative capital',
 'Judicial capital',
 'Year ofestablishment',
 'Former capital']

In [113]:
body=state.find('tbody')
d={col[0]:[],col[1]:[],col[2]:[],col[3]:[],col[4]:[],col[5]:[]}
for i in body.find_all('tr'):
    l=i.find_all('td')
    d[col[0]].append(l[0].text.strip())
    d[col[1]].append(l[1].text.strip())
    d[col[2]].append(l[2].text.strip())
    d[col[3]].append(l[3].text.strip())
    d[col[4]].append(l[4].text.strip())
    d[col[5]].append(l[5].text.strip())
df=pd.DataFrame(d)
df

,State,Administrative/Executive capital,Legislative capital,Judicial capital,Year ofestablishment,Former capital
0,Andhra Pradesh,Amaravati,Amaravati,Amaravati,1956,Hyderabad[a](1956–2014)
1,Arunachal Pradesh,Itanagar,Itanagar,Guwahati,1987,—
2,Assam,Dispur,Dispur,Guwahati,1972,Shillong[b] (1950–1972)
3,Bihar,Patna,Patna,Patna,1950,—
4,Chhattisgarh,Raipur[c],Raipur,Bilaspur,2000,—
5,Goa,Panaji[d],Porvorim,Mumbai,1987,—
6,Gujarat,Gandhinagar,Gandhinagar,Ahmedabad,1960,Ahmedabad (1960–1970)
7,Haryana,Chandigarh,Chandigarh,Chandigarh,1966,—
8,Himachal Pradesh,Shimla,Shimla (Summer)Dharamshala (Winter)[5],Shimla,1971,—
9,Jharkhand,Ranchi,Ranchi,Ranchi,2000,—
10,Karnataka,Bengaluru,Bengaluru (Summer)Belgaum (Winter),Bengaluru,1956,—
11,Kerala,Thiruvananthapuram,Thiruvananthapuram,Kochi[6],1956,—
12,Madhya Pradesh,Bhopal,Bhopal,Jabalpur,1956,—
13,Maharashtra,Mumbai[e],Mumbai (Summer)Nagpur (Winter),Mumbai,1960,—
14,Manipur,Imphal,Imphal,Imphal,1972,—
15,Meghalaya,Shillong,Shillong,Shillong,1972,—
16,Mizoram,Aizawl,Aizawl,Guwahati,1987,—
17,Nagaland,Kohima,Kohima,Guwahati,1963,—
18,Odisha,Bhubaneswar,Bhubaneswar,Cuttack,1950,—
19,Punjab,Chandigarh,Chandigarh,Chandigarh,1966,—
20,Rajasthan,Jaipur,Jaipur,Jodhpur,1950,—
21,Sikkim,Gangtok[f],Gangtok,Gangtok,1975,—
22,Tamil Nadu,Chennai[g],Chennai,Chennai,1956,—
23,Telangana,Hyderabad,Hyderabad,Hyderabad,2014,—
24,Tripura,Agartala,Agartala,Agartala,1972,—
25,Uttar Pradesh,Lucknow,Lucknow,Prayagraj,1950,—
26,Uttarakhand,Dehradun,Bhararisain (summer)[8]Dehradun (winter),Nainital,2000,—
27,West Bengal,Kolkata,Kolkata,Kolkata,1950,—

In [114]:
print(body)

<tbody>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Andhra_Pradesh" title="Andhra Pradesh">Andhra Pradesh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Amaravati" title="Amaravati">Amaravati</a>
</td>
<td>Amaravati
</td>
<td>Amaravati
</td>
<td>1956
</td>
<td><a href="https://en.wikipedia.org/wiki/Hyderabad" title="Hyderabad">Hyderabad</a><sup class="reference" id="cite_ref-3"><a href="#cite_note-3"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a></sup>(1956–2014)
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Arunachal_Pradesh" title="Arunachal Pradesh">Arunachal Pradesh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Itanagar" title="Itanagar">Itanagar</a>
</td>
<td>Itanagar
</td>
<td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
</td>
<td>1987
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Assam" title="Assam">Assam</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Dispur" title="Dispur">Dispur</a>
</td>
<td>Dispur
</td>
<td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
</td>
<td>1972
</td>
<td><a href="https://en.wikipedia.org/wiki/Shillong" title="Shillong">Shillong</a><sup class="reference" id="cite_ref-5"><a href="#cite_note-5"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a></sup> (1950–1972)
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Bihar" title="Bihar">Bihar</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Patna" title="Patna">Patna</a>
</td>
<td>Patna
</td>
<td>Patna
</td>
<td>1950
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Chhattisgarh" title="Chhattisgarh">Chhattisgarh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Raipur" title="Raipur">Raipur</a><sup class="reference" id="cite_ref-6"><a href="#cite_note-6"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a></sup>
</td>
<td>Raipur
</td>
<td><a href="https://en.wikipedia.org/wiki/Bilaspur,_Chhattisgarh" title="Bilaspur, Chhattisgarh">Bilaspur</a>
</td>
<td>2000
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Goa" title="Goa">Goa</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Panaji" title="Panaji">Panaji</a><sup class="reference" id="cite_ref-8"><a href="#cite_note-8"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a></sup>
</td>
<td><a href="https://en.wikipedia.org/wiki/Porvorim" title="Porvorim">Porvorim</a>
</td>
<td><a href="https://en.wikipedia.org/wiki/Mumbai" title="Mumbai">Mumbai</a>
</td>
<td>1987
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Gujarat" title="Gujarat">Gujarat</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Gandhinagar" title="Gandhinagar">Gandhinagar</a>
</td>
<td>Gandhinagar
</td>
<td><a href="https://en.wikipedia.org/wiki/Ahmedabad" title="Ahmedabad">Ahmedabad</a>
</td>
<td>1960
</td>
<td>Ahmedabad (1960–1970)
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Haryana" title="Haryana">Haryana</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
</td>
<td>Chandigarh
</td>
<td>Chandigarh
</td>
<td>1966
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Himachal_Pradesh" title="Himachal Pradesh">Himachal Pradesh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Shimla" title="Shimla">Shimla</a>
</td>
<td>Shimla (Summer)<br/><a href="https://en.wikipedia.org/wiki/Dharamshala" title="Dharamshala">Dharamshala</a> (Winter)<sup class="reference" id="cite_ref-9"><a href="#cite_note-9"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</td>
<td>Shimla
</td>
<td>1971
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Jharkhand" title="Jharkhand">Jharkhand</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Ranchi" title="Ranchi">Ranchi</a>
</td>
<td>Ranchi
</td>
<td>Ranchi
</td>
<td>2000
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Karnataka" title="Karnataka">Karnataka</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Bengaluru" title="Bengaluru">Bengaluru</a>
</td>
<td>Bengaluru (Summer)<br/><a href="https://en.wikipedia.org/wiki/Belgaum" title="Belgaum">Belgaum</a> (Winter)
</td>
<td>Bengaluru
</td>
<td>1956
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Kerala" title="Kerala">Kerala</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Thiruvananthapuram" title="Thiruvananthapuram">Thiruvananthapuram</a>
</td>
<td>Thiruvananthapuram
</td>
<td><a href="https://en.wikipedia.org/wiki/Kochi" title="Kochi">Kochi</a><sup class="reference" id="cite_ref-10"><a href="#cite_note-10"><span class="cite-bracket">[</span>6<span class="cite-bracket">]</span></a></sup>
</td>
<td>1956
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Madhya_Pradesh" title="Madhya Pradesh">Madhya Pradesh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Bhopal" title="Bhopal">Bhopal</a>
</td>
<td>Bhopal
</td>
<td><a href="https://en.wikipedia.org/wiki/Jabalpur" title="Jabalpur">Jabalpur</a>
</td>
<td>1956
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Maharashtra" title="Maharashtra">Maharashtra</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Mumbai" title="Mumbai">Mumbai</a><sup class="reference" id="cite_ref-11"><a href="#cite_note-11"><span class="cite-bracket">[</span>e<span class="cite-bracket">]</span></a></sup>
</td>
<td>Mumbai (Summer)<br/><a href="https://en.wikipedia.org/wiki/Nagpur" title="Nagpur">Nagpur</a> (Winter)
</td>
<td>Mumbai
</td>
<td>1960
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Manipur" title="Manipur">Manipur</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Imphal" title="Imphal">Imphal</a>
</td>
<td>Imphal
</td>
<td>Imphal
</td>
<td>1972
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Meghalaya" title="Meghalaya">Meghalaya</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Shillong" title="Shillong">Shillong</a>
</td>
<td>Shillong
</td>
<td>Shillong
</td>
<td>1972
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Mizoram" title="Mizoram">Mizoram</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Aizawl" title="Aizawl">Aizawl</a>
</td>
<td>Aizawl
</td>
<td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
</td>
<td>1987
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Nagaland" title="Nagaland">Nagaland</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Kohima" title="Kohima">Kohima</a>
</td>
<td>Kohima
</td>
<td><a href="https://en.wikipedia.org/wiki/Guwahati" title="Guwahati">Guwahati</a>
</td>
<td>1963
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Odisha" title="Odisha">Odisha</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Bhubaneswar" title="Bhubaneswar">Bhubaneswar</a>
</td>
<td>Bhubaneswar
</td>
<td><a href="https://en.wikipedia.org/wiki/Cuttack" title="Cuttack">Cuttack</a>
</td>
<td>1950
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Punjab,_India" title="Punjab, India">Punjab</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
</td>
<td>Chandigarh
</td>
<td>Chandigarh
</td>
<td>1966
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Rajasthan" title="Rajasthan">Rajasthan</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Jaipur" title="Jaipur">Jaipur</a>
</td>
<td>Jaipur
</td>
<td><a href="https://en.wikipedia.org/wiki/Jodhpur" title="Jodhpur">Jodhpur</a>
</td>
<td>1950
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Sikkim" title="Sikkim">Sikkim</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Gangtok" title="Gangtok">Gangtok</a><sup class="reference" id="cite_ref-13"><a href="#cite_note-13"><span class="cite-bracket">[</span>f<span class="cite-bracket">]</span></a></sup>
</td>
<td>Gangtok
</td>
<td>Gangtok
</td>
<td>1975
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Tamil_Nadu" title="Tamil Nadu">Tamil Nadu</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Chennai" title="Chennai">Chennai</a><sup class="reference" id="cite_ref-14"><a href="#cite_note-14"><span class="cite-bracket">[</span>g<span class="cite-bracket">]</span></a></sup>
</td>
<td>Chennai
</td>
<td>Chennai
</td>
<td>1956
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Telangana" title="Telangana">Telangana</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Hyderabad" title="Hyderabad">Hyderabad</a>
</td>
<td>Hyderabad
</td>
<td>Hyderabad
</td>
<td>2014
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Tripura" title="Tripura">Tripura</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Agartala" title="Agartala">Agartala</a>
</td>
<td>Agartala
</td>
<td>Agartala
</td>
<td>1972
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Uttar_Pradesh" title="Uttar Pradesh">Uttar Pradesh</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Lucknow" title="Lucknow">Lucknow</a>
</td>
<td>Lucknow
</td>
<td><a href="https://en.wikipedia.org/wiki/Prayagraj" title="Prayagraj">Prayagraj</a>
</td>
<td>1950
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/Uttarakhand" title="Uttarakhand">Uttarakhand</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Dehradun" title="Dehradun">Dehradun</a>
</td>
<td><a href="https://en.wikipedia.org/wiki/Bhararisain" title="Bhararisain">Bhararisain</a> (summer)<sup class="reference" id="cite_ref-15"><a href="#cite_note-15"><span class="cite-bracket">[</span>8<span class="cite-bracket">]</span></a></sup><br/>Dehradun (winter)
</td>
<td><a href="https://en.wikipedia.org/wiki/Nainital" title="Nainital">Nainital</a>
</td>
<td>2000
</td>
<td> —
</td></tr>
<tr>
<td><b><a href="https://en.wikipedia.org/wiki/West_Bengal" title="West Bengal">West Bengal</a></b>
</td>
<td><a href="https://en.wikipedia.org/wiki/Kolkata" title="Kolkata">Kolkata</a>
</td>
<td>Kolkata
</td>
<td>Kolkata
</td>
<td>1950
</td>
<td> —
<tfoot></tfoot></td></tr></tbody>

In [140]:
f=open('140 Essential Action Movies To Watch Now ｜ Rotten Tomatoes (5_28_2025 8：24：58 AM).html','r',encoding='utf-8')
res=f.read()
soup=BeautifulSoup(res,'html.parser')
box=soup.find('div','articleContentBody')
d={'name':[],'rating':[],'director':[]}

In [141]:
box=soup.find('div','articleContentBody')
print(len(box))

16

In [130]:
 d['name'].append(i.find('div',class_='article_movie_title').text.strip().split('\n')[0])

{'name': ['Running Scared'], 'rating': [], 'director': []}

In [133]:
box[0].text

'\n\n140 Essential Action Movies To Watch Now\nWelcome to our guide to the most Essential Action Movies! Where everyone enters…and only 140 leave. Which sounds like a lot, but when you’re considering thousands of action movies, it’s only the most thrilling, the most exciting, the most brutal, and the influential who make the cut!\nAction is a wide-open genre and term, and we endeavored to include something from every era, style, and movement of action movies. We have the classics (Die Hard, The French Connection), modern fan favorites (Hardcore Henry, John Wick), superhero blockbusters (Captain America: The Winter Soldier), and plenty from the macho ’80s (Commando, First Blood). Not to mention some action genre crossovers: sci-fi (Equilibrium), horror (They Live), and, of course, comedy (Beverly Hills Cop).\nInternationally, we reach as far as Hong Kong (Police Story, Hard-Boiled), Australia (The Road Warrior), England (Kingsman: The Secret Service), France (La Femme Nikita), Indonesia (The Raid: Redemption), Korea (The Villainess), and beyond.\nThese are the action movies whose influence can be seen in the films that followed. They spawned franchises, pushed back against time, defined and even expanded the genre. These are the badass movies that make audiences feel cooler from having seen them. In the interest of keeping the Essential Movies as tight and pure as possible, we excluded the genres of war, sports, Western, and samurai. Otherwise, a movie’s Tomatometer score was not a factor, so long as the plot was\xa0kicked forward in a hail of bullets, car chases, fist fights, and martial arts wizardry.\nNow, it’s time to pound faces and popcorn, with the 140 Essential Action Movies to watch now! —Alex Vo\n\n\n#140\n\n\n\n\n\n\n\n\n\n\nRunning Scared\n(1986)\n\n 63%\n\n\n\n\n#140\n\n\n\n\n\nCritics Consensus: Running Scared struggles to strike a consistent balance between violent action and humor, but the chemistry between its well-matched leads keeps things entertaining. \n\nSynopsis: Ray and Danny (Gregory Hines, Billy Crystal) are two Chicago police detectives hot on the trail of drug kingpin Julio  [More]\n\n\n\n Starring: \nGregory Hines\n , Billy Crystal\n , Jimmy Smits\n , Steven Bauer\n\n\n\n Directed By: \nPeter Hyams\n \n\n\n\n\n#139\n\n\n\n\n\n\n\n\n\n\nEquilibrium\n(2002)\n\n 40%\n\n\n\n\n#139\n\n\n\n\n\nCritics Consensus: Equilibrium is a reheated mishmash of other sci-fi movies. \n\nSynopsis: In a futuristic world, a regime has eliminated war by suppressing emotions: books, art and music are strictly forbidden and  [More]\n\n\n\n Starring: \nChristian Bale\n , Emily Watson\n , Taye Diggs\n , Angus Macfadyen\n\n\n\n Directed By: \nKurt Wimmer\n \n\n\n\n\n#138\n\n\n\n\n\n\n\n\n\n\nHero\n(2002)\n\n 94%\n\n\n\n\n#138\n\n\n\n\n\nCritics Consensus: With death-defying action sequences and epic historic sweep, Hero offers everything a martial arts fan could ask for. \n\nSynopsis: In this visually arresting martial arts epic set in ancient China, an unnamed fighter (Jet Li) is being honored for  [More]\n\n\n\n Starring: \nJet Li\n , Tony Leung Chiu Wai\n , Maggie Cheung\n , Donnie Yen\n\n\n\n Directed By: \nYimou Zhang\n \n\n\n\n\n#137\n\n\n\n\n\n\n\n\n\n\nRoad House\n(1989)\n\n 44%\n\n\n\n\n#137\n\n\n\n\n\nCritics Consensus: Whether Road House is simply bad or so bad it\'s good depends largely on the audience\'s fondness for Swayze -- and tolerance for violently cheesy action. \n\nSynopsis: The Double Deuce is the meanest, loudest and rowdiest bar south of the Mason-Dixon Line, and Dalton (Patrick Swayze) has  [More]\n\n\n\n Starring: \nPatrick Swayze\n , Kelly Lynch\n , Sam Elliott\n , Ben Gazzara\n\n\n\n Directed By: \nRowdy Herrington\n \n\n\n\n\n#136\n\n\n\n\n\n\n\n\n\n\nUnstoppable\n(2010)\n\n 87%\n\n\n\n\n#136\n\n\n\n\n\nCritics Consensus: As fast, loud, and relentless as the train at the center of the story, Unstoppable is perfect popcorn entertainment -- and director Tony Scott\'s best movie in years. \n\nSynopsis: When a massive, unmanned locomotive roars out of control, the threat is more ominous than just a derailment. The train  [More]\n\n\n\n Starring: \nDenzel Washington\n , Chris Pine\n , Rosario Dawson\n , Kevin Dunn\n\n\n\n Directed By: \nTony Scott\n \n\n\n\n\n#135\n\n\n\n\n\n\n\n\n\n\nShaft\n(1971)\n\n 88%\n\n\n\n\n#135\n\n\n\n\n\nCritics Consensus: This is the man that would risk his neck for his brother, man. Can you dig it? \n\nSynopsis: John Shaft (Richard Roundtree) is the ultimate in suave black detectives. He first finds himself up against Bumpy (Moses Gunn),  [More]\n\n\n\n Starring: \nRichard Roundtree\n , Moses Gunn\n , Christopher St. John\n , Charles Cioffi\n\n\n\n Directed By: \nGordon Parks\n \n\n\n\n\n#134\n\n\n\n\n\n\n\n\n\n\nThe Villainess\n(2017)\n\n 85%\n\n\n\n\n#134\n\n\n\n\n\nCritics Consensus: The Villainess offers enough pure kinetic thrills to satisfy genre enthusiasts -- and carve out a bloody niche for itself in modern Korean action cinema. \n\nSynopsis: Honed from childhood to be an elite assassin, Sook-hee embarks on a rampage of violence and revenge to finally earn  [More]\n\n\n\n Starring: \nKim Ok-bin\n , Shin Ha-kyun\n , Sung-joon\n , Kim Seo-hyung\n\n\n\n Directed By: \nJeong Byeong-gil\n \n\n\n\n\n#133\n\n\n\n\n\n\n\n\n\n\nHighlander\n(1986)\n\n 69%\n\n\n\n\n#133\n\n\n\n\n\nCritics Consensus: People hate Highlander because it\'s cheesy, bombastic, and absurd. And people love it for the same reasons. \n\nSynopsis: When the mystical Russell Nash (Christopher Lambert) kills a man in a sword fight in a New York City parking  [More]\n\n\n\n Starring: \nChristopher Lambert\n , Sean Connery\n , Roxanne Hart\n , Clancy Brown\n\n\n\n Directed By: \nRussell Mulcahy\n \n\n\n\n\n#132\n\n\n\n\n\n\n\n\n\n\nDie Hard 2\n(1990)\n\n 69%\n\n\n\n\n#132\n\n\n\n\n\nCritics Consensus: It lacks the fresh thrills of its predecessor, but Die Hard 2 still works as an over-the-top -- and reasonably taut -- big-budget sequel, with plenty of set pieces to paper over the plot deficiencies. \n\nSynopsis: A year after his heroics in L.A, detective John McClane (Bruce Willis) is mixed up in another terrorist plot, this  [More]\n\n\n\n Starring: \nBruce Willis\n , Bonnie Bedelia\n , William Atherton\n , Reginald VelJohnson\n\n\n\n Directed By: \nRenny Harlin\n \n\n\n\n\n#131\n\n\n\n\n\n\n\n\n\n\nNational Treasure\n(2004)\n\n 46%\n\n\n\n\n#131\n\n\n\n\n\nCritics Consensus: National Treasure is no treasure, but it\'s a fun ride for those who can forgive its highly improbable plot. \n\nSynopsis: Historian and code-breaker Ben Gates (Nicolas Cage) has been searching his whole life for a rumored treasure dating back to  [More]\n\n\n\n Starring: \nNicolas Cage\n , Diane Kruger\n , Justin Bartha\n , Sean Bean\n\n\n\n Directed By: \nJon Turteltaub\n \n\n\n\n\n#130\n\n\n\n\n\n\n\n\n\n\nThe Protector\n(2005)\n\n 53%\n\n\n\n\n#130\n\n\n\n\n\nCritics Consensus: Despite some impressive fight scenes, this trimmed-down version of the Thai action pic is an off-putting mix of scant plot, choppy editing, and confusing subtitles and dubbing. \n\nSynopsis: A young fighter (Tony Jaa) travels to Australia to retrieve stolen elephants that were promised originally to the king of  [More]\n\n\n\n Starring: \nTony Jaa\n , Johnny Nguyen\n , Nathan Jones\n , Phetthai Vongkumlao\n\n\n\n Directed By: \nPrachya Pinkaew\n \n\n\n\n\n#129\n\n\n\n\n\n\n\n\n\n\nRevenge\n(2017)\n\n 92%\n\n\n\n\n#129\n\n\n\n\n\nCritics Consensus: Revenge slices and dices genre tropes, working within an exploitation framework while adding a timely -- yet never less than viscerally thrilling -- feminist spin. \n\nSynopsis: Jen is enjoying a romantic getaway with her wealthy boyfriend -- until his two sleazy friends arrive for an unannounced  [More]\n\n\n\n Starring: \nMatilda Anna Ingrid Lutz\n , Kevin Janssens\n , Vincent Colombe\n , Guillaume Bouchède\n\n\n\n Directed By: \nCoralie Fargeat\n \n\n\n\n\n#128\n\n\n\n\n\n\n\n\n\n\nEl Mariachi\n(1992)\n\n 91%\n\n\n\n\n#128\n\n\n\n\n\nCritics Consensus: Made on a shoestring budget, El Mariachi\'s story is not new. However, the movie has so much energy that it\'s thoroughly enjoyable. \n\nSynopsis: El Mariachi (Carlos Gallardo) is a traveling guitar player with the modest desire to play music for a living. Looking  [More]\n\n\n\n Starring: \nCarlos Gallardo\n , Consuelo Gómez\n , Reinol Martinez\n , Peter Marquardt\n\n\n\n Directed By: \nRobert Rodriguez\n \n\n\n\n\n#127\n\n\n\n\n\n\n\n\n\n\nA Touch of Zen\n(1971)\n\n 97%\n\n\n\n\n#127\n\n\n\n\n\nCritics Consensus: A brilliantly directed feast for the eyes with an epic story to match, A Touch of Zen marks a groundbreaking achievement in the wuxia genre. \n\nSynopsis: Ku Shen Chai (Chun Shih), an unmotivated artist in his early 30s, still lives with his mother, but he is  [More]\n\n\n\n Starring: \nFeng Hsu\n , Chun Shih\n , Pai Ying\n , Roy Chiao\n\n\n\n Directed By: \nKing Hu\n \n\n\n\n\n#126\n\n\n\n\n\n\n\n\n\n\nTop Gun\n(1986)\n\n 59%\n\n\n\n\n#126\n\n\n\n\n\nCritics Consensus: Though it features some of the most memorable and electrifying aerial footage shot with an expert eye for action, Top Gun offers too little for non-adolescent viewers to chew on when its characters aren\'t in the air. \n\nSynopsis: The Top Gun Naval Fighter Weapons School is where the best of the best train to refine their elite flying  [More]\n\n\n\n Starring: \nTom Cruise\n , Kelly McGillis\n , Anthony Edwards\n , Val Kilmer\n\n\n\n Directed By: \nTony Scott\n \n\n\n\n\n#125\n\n\n\n\n\n\n\n\n\n\nCon Air\n(1997)\n\n 58%\n\n\n\n\n#125\n\n\n\n\n\nCritics Consensus: Con Air won\'t win any awards for believability - and all involved seem cheerfully aware of it, making some of this blockbuster action outing\'s biggest flaws fairly easy to forgive. \n\nSynopsis: Just-paroled army ranger Cameron Poe (Nicolas Cage) is headed back to his wife (Monica Potter), but must fly home aboard  [More]\n\n\n\n Starring: \nNicolas Cage\n , John Cusack\n , John Malkovich\n , Steve Buscemi\n\n\n\n Directed By: \nSimon West\n \n\n\n\n\n#124\n\n\n\n\n\n\n\n\n\n\nThe Expendables 2\n(2012)\n\n 68%\n\n\n\n\n#124\n\n\n\n\n\nCritics Consensus: Taut, violent, and suitably self-deprecating, The Expendables 2 gives classic action fans everything they can reasonably expect from a star-studded shoot-\'em-up -- for better and for worse. \n\nSynopsis: Mercenary leader Barney Ross (Sylvester Stallone), Lee Christmas (Jason Statham) and the rest of the Expendables team reunite when Mr.  [More]\n\n\n\n Starring: \nSylvester Stallone\n , Jason Statham\n , Jet Li\n , Dolph Lundgren\n\n\n\n Directed By: \nSimon West\n \n\n\n\n\n#123\n\n\n\n\n\n\n\n\n\n\nThe Mummy\n(1999)\n\n 62%\n\n\n\n\n#123\n\n\n\n\n\nCritics Consensus: It\'s difficult to make a persuasive argument for The Mummy as any kind of meaningful cinematic achievement, but it\'s undeniably fun to watch. \n\nSynopsis: The Mummy is a rousing, suspenseful and horrifying epic about an expedition of treasure-seeking explorers in the Sahara Desert in  [More]\n\n\n\n Starring: \nBrendan Fraser\n , Rachel Weisz\n , John Hannah\n , Arnold Vosloo\n\n\n\n Directed By: \nStephen Sommers\n \n\n\n\n\n#122\n\n\n\n\n\n\n\n\n\n\nMr. & Mrs. Smith\n(2005)\n\n 60%\n\n\n\n\n#122\n\n\n\n\n\nCritics Consensus: Although this action-romance suffers from weak writing and one too many explosions, the chemistry generated by onscreen couple Pitt and Jolie is palpable enough to make this a thoroughly enjoyable summer action flick. \n\nSynopsis: John (Brad Pitt) and Jane Smith (Angelina Jolie), a couple in a stagnating marriage, live a deceptively mundane existence. However,  [More]\n\n\n\n Starring: \nBrad Pitt\n , Angelina Jolie\n , Vince Vaughn\n , Adam Brody\n\n\n\n Directed By: \nDoug Liman\n \n\n\n\n\n#121\n\n\n\n\n\n\n\n\n\n\nRush Hour\n(1998)\n\n 62%\n\n\n\n\n#121\n\n\n\n\n\nCritics Consensus: While it won\'t win any awards for originality, the combustible chemistry between its stars means Rush Hour hits just as hard on either side of the action-comedy divide. \n\nSynopsis: When a Chinese diplomat\'s daughter is kidnapped in Los Angeles, he calls in Hong Kong Detective Inspector Lee (Jackie Chan)  [More]\n\n\n\n Starring: \nJackie Chan\n , Chris Tucker\n , Tom Wilkinson\n , Elizabeth Peña\n\n\n\n Directed By: \nBrett Ratner\n \n\n\n\n\n#120\n\n\n\n\n\n\n\n\n\n\nThe Equalizer\n(2014)\n\n 61%\n\n\n\n\n#120\n\n\n\n\n\nCritics Consensus: The Equalizer is more stylishly violent than meaningful, but with Antoine Fuqua behind the cameras and Denzel Washington dispensing justice, it delivers. \n\nSynopsis: Robert McCall (Denzel Washington), a man of mysterious origin who believes he has put the past behind him, dedicates himself  [More]\n\n\n\n Starring: \nDenzel Washington\n , Marton Csokas\n , Chloë Grace Moretz\n , David Harbour\n\n\n\n Directed By: \nAntoine Fuqua\n \n\n\n\n\n#119\n\n\n\n\n\n\n\n\n\n\nCaptain America: Civil War\n(2016)\n\n 90%\n\n\n\n\n#119\n\n\n\n\n\nCritics Consensus: Captain America: Civil War begins the next wave of Marvel movies with an action-packed superhero blockbuster boasting a decidedly non-cartoonish plot and the courage to explore thought-provoking themes. \n\nSynopsis: Political pressure mounts to install a system of accountability when the actions of the Avengers lead to collateral damage. The  [More]\n\n\n\n Starring: \nChris Evans\n , Robert Downey Jr.\n , Scarlett Johansson\n , Sebastian Stan\n\n\n\n Directed By: \nAnthony Russo\n , Joe Russo\n \n\n\n\n\n#118\n\n\n\n\n\n\n\n\n\n\nAir Force One\n(1997)\n\n 79%\n\n\n\n\n#118\n\n\n\n\n\nCritics Consensus: This late-period Harrison Ford actioner is full of palpable, if not entirely seamless, thrills. \n\nSynopsis: After making a speech in Moscow vowing to never negotiate with terrorists, President James Marshall boards Air Force One with  [More]\n\n\n\n Starring: \nHarrison Ford\n , Gary Oldman\n , Glenn Close\n , Wendy Crewson\n\n\n\n Directed By: \nWolfgang Petersen\n \n\n\n\n\n#117\n\n\n\n\n\n\n\n\n\n\nBloodsport\n(1988)\n\n 48%\n\n\n\n\n#117\n\n\n\n\n\nCritics Consensus: This is where it all began for the Muscles from Brussels, but beyond Van Damme\'s athleticism, Bloodsport is a cliched, virtually plotless exercise in action movie recycling. \n\nSynopsis: U.S. soldier Frank Dux (Jean-Claude Van Damme) has come to Hong Kong to be accepted into the Kumite, a highly  [More]\n\n\n\n Starring: \nJean-Claude Van Damme\n , Donald Gibb\n , Leah Ayres\n , Norman Burton\n\n\n\n Directed By: \nNewt Arnold\n \n\n\n\n\n#116\n\n\n\n\n\n\n\n\n\n\nBlade\n(1998)\n\n 58%\n\n\n\n\n#116\n\n\n\n\n\nCritics Consensus: Though some may find the plot a bit lacking, Blade\'s action is fierce, plentiful, and appropriately stylish for a comic book adaptation. \n\nSynopsis: A half-mortal, half-immortal is out to avenge his mother\'s death and rid the world of vampires. The modern-day technologically advanced  [More]\n\n\n\n Starring: \nWesley Snipes\n , Stephen Dorff\n , Kris Kristofferson\n , N\'Bushe Wright\n\n\n\n Directed By: \nStephen Norrington\n \n\n\n\n\n#115\n\n\n\n\n\n\n\n\n\n\nBad Boys\n(1995)\n\n 44%\n\n\n\n\n#115\n\n\n\n\n\nCritics Consensus: Bad Boys stars Will Smith and Martin Lawrence have enjoyable chemistry; unfortunately, director Michael Bay too often drowns it out with set pieces and explosions in place of an actual story. \n\nSynopsis: Miami-Dade detectives Mike Lowrey (Will Smith) and Marcus Burnett (Martin Lawrence) blow a fuse when $100 million worth of heroin  [More]\n\n\n\n Starring: \nMartin Lawrence\n , Will Smith\n , Téa Leoni\n , Tchéky Karyo\n\n\n\n Directed By: \nMichael Bay\n \n\n\n\n\n#114\n\n\n\n\n\n\n\n\n\n\nDie Hard With a Vengeance\n(1995)\n\n 60%\n\n\n\n\n#114\n\n\n\n\n\nCritics Consensus: Die Hard with a Vengeance benefits from Bruce Willis and Samuel L. Jackson\'s barbed interplay, but clatters to a bombastic finish in a vain effort to cover for an overall lack of fresh ideas. \n\nSynopsis: Detective John McClane (Bruce Willis) is now divorced, alcoholic and jobless after getting fired for his reckless behavior and bad  [More]\n\n\n\n Starring: \nBruce Willis\n , Jeremy Irons\n , Samuel L. Jackson\n , Graham Greene\n\n\n\n Directed By: \nJohn McTiernan\n \n\n\n\n\n#113\n\n\n\n\n\n\n\n\n\n\nThe Running Man\n(1987)\n\n 67%\n\n\n\n\n#113\n\n\n\n\n\nCritics Consensus: The Running Man is winking sci-fi satire with ridiculous clothes and workmanlike direction. \n\nSynopsis: In the year 2019, America is a totalitarian state where the favorite television program is "The Running Man" -- a  [More]\n\n\n\n Starring: \nArnold Schwarzenegger\n , Maria Conchita Alonso\n , Richard Dawson\n , Yaphet Kotto\n\n\n\n Directed By: \nPaul Michael Glaser\n \n\n\n\n\n#112\n\n\n\n\n\n\n\n\n\n\nCode of Silence\n(1985)\n\n 68%\n\n\n\n\n#112\n\n\n\n\n\nCritics Consensus: No consensus yet. \n\nSynopsis: In Chicago, honor-driven Sgt. Eddie Cusack (Chuck Norris) and his team stake out a drug exchange involving notorious drug czar  [More]\n\n\n\n Starring: \nChuck Norris\n , Henry Silva\n , Bert Remsen\n , Mike Genovese\n\n\n\n Directed By: \nAndrew Davis\n \n\n\n\n\n#111\n\n\n\n\n\n\n\n\n\n\nShoot \'Em Up\n(2007)\n\n 67%\n\n\n\n\n#111\n\n\n\n\n\nCritics Consensus: As preposterous and over-the-top as Shoot \'Em Up may be, its humor and non-stop action make for a very enjoyable film. \n\nSynopsis: After saving a newborn infant from assassins, carrot-crunching gunman Mr. Smith (Clive Owen) teams up with a prostitute named DQ  [More]\n\n\n\n Starring: \nClive Owen\n , Paul Giamatti\n , Monica Bellucci\n , Daniel Pilon\n\n\n\n Directed By: \nMichael Davis\n \n\n\n\n\n#110\n\n\n\n\n\n\n\n\n\n\nCrank\n(2006)\n\n 62%\n\n\n\n\n#110\n\n\n\n\n\nCritics Consensus: Crank\'s assaultive style and gleeful depravity may turn off casual action fans, but audiences seeking a strong dose of adrenaline will be thrilled by Jason Statham\'s raucous race against mortality. \n\nSynopsis: Chev Chelios (Jason Statham), a hit man wanting to go straight, lets his latest target slip away, then he awakes  [More]\n\n\n\n Starring: \nJason Statham\n , Amy Smart\n , Jose Pablo Cantillo\n , Efren Ramirez\n\n\n\n Directed By: \nMark Neveldine\n , Brian Taylor\n \n\n\n\n\n#109\n\n\n\n\n\n\n\n\n\n\nMachete\n(2010)\n\n 70%\n\n\n\n\n#109\n\n\n\n\n\nCritics Consensus: Machete is messy, violent, shallow, and tasteless -- and that\'s precisely the point of one of the summer\'s most cartoonishly enjoyable films. \n\nSynopsis: After nearly being killed during a violent fight with a powerful drug lord, a former Mexican Federale known as Machete  [More]\n\n\n\n Starring: \nDanny Trejo\n , Robert De Niro\n , Jessica Alba\n , Steven Seagal\n\n\n\n Directed By: \nRobert Rodriguez\n , Ethan Maniquis\n \n\n\n\n\n#108\n\n\n\n\n\n\n\n\n\n\nDrive\n(2011)\n\n 93%\n\n\n\n\n#108\n\n\n\n\n\nCritics Consensus: With its hyper-stylized blend of violence, music, and striking imagery, Drive represents a fully realized vision of arthouse action. \n\nSynopsis: Driver is a skilled Hollywood stuntman who moonlights as a getaway driver for criminals. Though he projects an icy exterior,  [More]\n\n\n\n Starring: \nRyan Gosling\n , Carey Mulligan\n , Bryan Cranston\n , Albert Brooks\n\n\n\n Directed By: \nNicolas Winding Refn\n \n\n\n\n\n#107\n\n\n\n\n\n\n\n\n\n\nBatman\n(1989)\n\n 76%\n\n\n\n\n#107\n\n\n\n\n\nCritics Consensus: An eerie, haunting spectacle, Batman succeeds as dark entertainment, even if Jack Nicholson\'s Joker too often overshadows the title character. \n\nSynopsis: Having witnessed his parents\' brutal murder as a child, millionaire philanthropist Bruce Wayne (Michael Keaton) fights crime in Gotham City  [More]\n\n\n\n Starring: \nJack Nicholson\n , Michael Keaton\n , Kim Basinger\n , Robert Wuhl\n\n\n\n Directed By: \nTim Burton\n \n\n\n\n\n#106\n\n\n\n\n\n\n\n\n\n\nUnder Siege\n(1992)\n\n 83%\n\n\n\n\n#106\n\n\n\n\n\nCritics Consensus: A well-directed action thriller that makes the most of its confined setting, Under Siege marks a high point for early \'90s action 